import { StyleSheet } from 'react-native';
import { theme } from '../../../global/styles/themes';

export const styles = StyleSheet.create({
    container: { flex: 1 },
    content: { padding: 24, paddingBottom: 50 },
    label: { fontFamily: theme.fonts.title, fontSize: 18, marginTop: 14, marginBottom: 4 },
    sectionTitle: { fontFamily: theme.fonts.title, fontSize: 21, marginTop: 28, marginBottom: 8 },
    input: {
        width: '100%',
        minHeight: 46,
        backgroundColor: theme.colors.bar,
        color: '#FFFFFF',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#3E3E3E',
        fontFamily: theme.fonts.subtitle,
        fontSize: 17,
        lineHeight: 22,
        paddingHorizontal: 14,
        paddingVertical: 10,
        marginBottom: 9,
    },
    reflection: { minHeight: 130 },
    emotions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    emotionButton: {
        width: '48%',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#C8C8C8',
        backgroundColor: '#FFFFFF',
    },
    emotionSelected: { backgroundColor: theme.colors.primary, borderColor: theme.colors.secondary },
    emotionText: { fontFamily: theme.fonts.title, fontSize: 16 },
    linkRow: { flexDirection: 'row', alignItems: 'center' },
    linkInput: { flex: 1 },
    openLink: { padding: 12, marginLeft: 6, marginBottom: 9 },
    photo: { width: '100%', height: 210, borderRadius: 8, backgroundColor: '#D9D9D9' },
    video: { width: '100%', height: 220, borderRadius: 8, backgroundColor: '#000000' },
    mediaActions: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
    mediaButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: theme.colors.primary,
        borderRadius: 8,
        paddingHorizontal: 14,
        height: 44,
    },
    mediaText: { fontFamily: theme.fonts.title, fontSize: 15 },
    removeButton: { padding: 12, marginLeft: 6 },
    saveArea: { marginTop: 32 },
});
